apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.operatorserviceaccount.name }}
  namespace: {{ .Values.operatorserviceaccount.namespace }}

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.agentserviceaccount.name }}
  namespace: {{ .Values.agentserviceaccount.namespace }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.operatorrole.name }}
  namespace: {{ .Values.operatorrole.namespace }}
rules:
- apiGroups: ["", "power.intel.com", "apps", "coordination.k8s.io"]
  resources: ["powerconfigs", "powerconfigs/status", "powerprofiles", "powerprofiles/status", "events", "daemonsets", "configmaps", "configmaps/status", "leases", "uncores"]
  verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.operatorrolebinding.name }}
  namespace: {{ .Values.operatorrolebinding.namespace }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.operatorrolebinding.serviceaccount.name }}
  namespace: {{ .Values.operatorrolebinding.serviceaccount.namespace }}
roleRef:
  kind: Role
  name: {{ .Values.operatorrolebinding.rolename }}
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.operatorclusterrole.name }}
rules:
- apiGroups: ["", "power.intel.com", "apps"]
  resources: ["nodes", "nodes/status", "configmaps", "configmaps/status", "powerconfigs", "powerconfigs/status", "powerprofiles", "powerprofiles/status", "powerworkloads", "powerworkloads/status", "powernodes", "powernodes/status", "events", "daemonsets", "uncores"]
  verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.operatorclusterrolebinding.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.operatorclusterrolebinding.serviceaccount.name }}
  namespace: {{ .Values.operatorclusterrolebinding.serviceaccount.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.operatorclusterrolebinding.clusterrolename }}
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.agentclusterrole.name }}
rules:
- apiGroups: ["", "batch", "power.intel.com"]
  resources: ["nodes", "nodes/status", "pods", "pods/status", "cronjobs", "cronjobs/status", "powerprofiles", "powerprofiles/status", "powerworkloads", "powerworkloads/status", "powernodes", "powernodes/status", "cstates", "cstates/status", "timeofdays", "timeofdays/status", "timeofdaycronjobs", "timeofdaycronjobs/status", "uncores"]
  verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.agentclusterrolebinding.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.agentclusterrolebinding.serviceaccount.name }}
  namespace: {{ .Values.agentclusterrolebinding.serviceaccount.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.agentclusterrolebinding.clusterrolename }}
  apiGroup: rbac.authorization.k8s.io
