# permissions for end users to edit cstates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cstates-editor-role
rules:
  - apiGroups:
      - power.intel.com
    resources:
      - cstates
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - power.intel.com
    resources:
      - cstates/status
    verbs:
      - get
