kind: Pod
apiVersion: v1
spec:
  containers:
  - name: ubuntu-env
    image: amr-registry.caas.intel.com/owr/ubuntu:20.04
    tty: true
    imagePullPolicy: IfNotPresent
    command: ["cat"]
  - name: abi-env
    image: amr-registry.caas.intel.com/owr/abi_lnx:latest
    tty: true
    imagePullPolicy: Always
    command: ["cat"]
  - name: trivy-env
    image: aquasec/trivy
    tty: true
    imagePullPolicy: IfNotPresent
    command: ["cat"]
  - name: kubesec-env
    image: kubesec/kubesec
    tty: true
    imagePullPolicy: Always
  - name: alpine-env
    image: alpine
    tty: true
    imagePullPolicy: IfNotPresent
    command: ["cat"]
  - name: hadolint-env
    image: hadolint/hadolint:latest-debian
    tty: true
    imagePullPolicy: Always
    command: ["cat"]
  - name: shellcheck-env
    image: koalaman/shellcheck-alpine
    tty: true
    imagePullPolicy: Always
    command: ["cat"]
  - name: kaniko-env
    image: gcr.io/kaniko-project/executor:debug
    tty: true
    imagePullPolicy: IfNotPresent
    command: ["/busybox/sleep","infinity"]
    # ephemeral image registry, available at localhost:5000 only for the lifetime of the pipeline
  - name: image-registry
    image: registry:2
    imagePullPolicy: IfNotPresent
