apiVersion: power.intel.com/v1
kind: PowerConfig
metadata:
  name: {{ .Values.powerconfig.name }}
  namespace: {{ .Values.powerconfig.namespace }}
spec:
  powerNodeSelector:
    feature.node.kubernetes.io/power-node: "true"
  powerProfiles:
  - "performance"
  - "balance-performance"
  - "balance-power"
