apiVersion: power.intel.com/v1
kind: Uncore
metadata:
  labels:
    app.kubernetes.io/name: uncore
    app.kubernetes.io/instance: uncore-sample
    app.kubernetes.io/part-of: kubernetes-power-manager
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubernetes-power-manager
  name: uncore-sample
spec:
# TODO(user): Add fields here
