apiVersion: power.intel.com/v1
kind: PowerProfile
metadata:
  name: shared
  namespace: intel-power
spec:
  name: "shared"
  max: 1000
  min: 1000
  # A shared PowerProfile must have the EPP value of 'power'
  epp: "power"
