apiVersion: power.intel.com/v1
kind: TimeOfDay
metadata:
  name: timeofday-sample
  namespace: intel-power
spec:
  timeZone: "Eire"
  schedule:
    - time: "14:24"
      # this sets the profile for the shared pool
      powerProfile: balance-performance
      # this transitions a pod with the given name from one profile to another
      pods: 
        four-pod-v2: 
          performance: balance-performance
        four-pod-v4:
          balance-power: performance
      # this field simply takes a cstate spec
      cState: 
        sharedPoolCStates:
          C1: false
          C6: true
    - time: "14:26"
      powerProfile: performance
      cState: 
        sharedPoolCStates:
          C1: true
          C6: false
    - time: "14:28"
      powerProfile: balance-power
  reservedCPUs: [0,1]