{{- include "manager-chart-library.namespace" . }}
---
{{- include "manager-chart-library.operatorserviceaccount" . }}
---
{{- include "manager-chart-library.agentserviceaccount" . }}
---
{{- include "manager-chart-library.operatorrole" . }}
---
{{- include "manager-chart-library.operatorrolebinding" . }}
---
{{- include "manager-chart-library.operatorclusterrole" . }}
---
{{- include "manager-chart-library.operatorclusterrolebinding" . }}
---
{{- include "manager-chart-library.agentclusterrole" . }}
---
{{- include "manager-chart-library.agentclusterrolebinding" . }}
---
{{- include "manager-chart-library.deployment" . }}
---
{{- include "manager-chart-library.powerconfig" . }}
---
{{- if  eq (semver "2.2.0" | (semver .Chart.Version).Compare) 1}}
{{- include "manager-chart-library.new-shared-profile" . }}
{{- else }}
{{- include "manager-chart-library.shared-profile" . }}
{{- end }}
# above checks the version to decide which template to use