pipeline {
    agent {
     label 'pwr-mgr-tester'
    }
    tools { go '1.19.1' }
    triggers {
        cron('30 23 * * *') //run at 23:30:00
    }
    environment {
        GO114MODULE = 'on'
        CGO_ENABLED = 0
    }
    stages {
        stage('Build') {
            steps {
                echo 'Building..'
                sh 'make build'
                sh 'make images'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
                sh 'make test'
            }
        }
        stage('Style'){
            steps{
                sh 'curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | bash -s -- -b . v1.53.3'
                sh 'make golangci'
            }
            }
    }
}

